---
- name: Install gnome
  tags: gnome
  block:
    - name: Install xorg
      community.general.pacman:
        name:
          - xorg
          - xorg-server
    - name: Install gnome packages
      community.general.pacman:
        name:
          - gdm
          - gnome
          - gnome-extra
          - gnome-shell-extension-appindicator
          - power-profiles-daemon
          - networkmanager
          - xorg-server
        state: present
        update_cache: yes
    - name: Install gnome extensions
      community.general.pacman:
        name:
          - gnome-shell-extension-appindicator
        state: present
        update_cache: yes
    - name: Install gnome extensions from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-desktop-icons-ng
          - gnome-shell-extension-just-perfection-desktop-git
      become: yes
      become_user: aur_builder
    - name: "Enable gdm"
      shell: systemctl enable gdm
    - name: "Enable NetworkManager"
      shell: systemctl enable NetworkManager
    - name: "Enable power-profiles-daemon"
      shell: systemctl enable power-profiles-daemon
    
- name: Configure gnome
  tags: [gnome, gnome-config]
  block:
    - name: Use gtk theme 'Yaru-dark'
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
      become: yes
      become_user: '{{ username }}'

    - name: Use gnome shell theme 'Yaru-dark'
      dconf:
        key: "/org/gnome/shell/extensions/user-theme/name"
        value: "'Adwaita-dark'"
    
    - name: Set font hinting to slight (as ubuntu does)
      dconf:
        key: "/org/gnome/desktop/interface/font-hinting"
        value: "'slight'"
    
    - name: Set gtk font default font
      dconf:
        key: "/org/gnome/desktop/interface/font-name"
        value: "'Ubuntu 12'"
    
    - name: Set document default font
      dconf:
        key: "/org/gnome/desktop/interface/document-font-name"
        value: "'Ubuntu 12'"
    
    - name: Set default monospace font
      dconf:
        key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'IBM Plex Mono 12'"

    - name: Center new windows
      dconf:
        key: "/org/gnome/mutter/center-new-windows"
        value: "true"
      
    - name: Show battery percentage
      dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"
    
    - name: Show date on clock
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-date"
        value: "true"
      
    - name: Show seconds on clock
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-seconds"
        value: "true"

    - name: Show weekdays on calendar
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"

    - name: Show week number on calendar
      dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: "true"

    - name: Use exactly 4 workspaces
      dconf:
        key: "/org/gnome/desktop/wm/preferences/num-workspaces"
        value: "4"

    - name: Use workspaces on all monitors
      dconf:
        key: "/org/gnome/mutter/workspaces-only-on-primary"
        value: "false"

    - name: Enable mouse natural scrool
      dconf:
        key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
        value: "true"

    - name: Set 'move to workspace 1' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1"
        value: "['<Shift><Super>F1']"

    - name: Set 'move to workspace 2' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2"
        value: "['<Shift><Super>F2']"

    - name: Set 'move to workspace 3' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3"
        value: "['<Shift><Super>F3']"

    - name: Set 'move to workspace 4' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4"
        value: "['<Shift><Super>F4']"

    - name: Set 'switch to workspace 1' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
        value: "['<Super>1']"

    - name: Set 'switch to workspace 2' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
        value: "['<Super>2']"

    - name: Set 'switch to workspace 3' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
        value: "['<Super>3']"

    - name: Set 'switch to workspace 4' keyboard shortcut
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
        value: "['<Super>4']"
    
    - name: Disable 'switch-to-application-1' keyboard shortcut
      dconf:
        key: "/org/gnome/shell/keybindings/switch-to-application-1"
        value: "@as []"
    - name: Disable 'switch-to-application-2' keyboard shortcut
      dconf:
        key: "/org/gnome/shell/keybindings/switch-to-application-2"
        value: "@as []"
    - name: Disable 'switch-to-application-3' keyboard shortcut
      dconf:
        key: "/org/gnome/shell/keybindings/switch-to-application-3"
        value: "@as []"
    - name: Disable 'switch-to-application-4' keyboard shortcut
      dconf:
        key: "/org/gnome/shell/keybindings/switch-to-application-4"
        value: "@as []"

    - name: Disable dash-to-dock hotkeys-1
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/app-hotkey-1"
        value: "@as []"
    - name: Disable dash-to-dock hotkeys-2
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/app-hotkey-2"
        value: "@as []"
    - name: Disable dash-to-dock hotkeys-3
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/app-hotkey-3"
        value: "@as []"
    - name: Disable dash-to-dock hotkeys-4
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/app-hotkey-4"
        value: "@as []"
      
    - name: Close windows with super+shift+q
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/close"
        value: "['<Shift><Super>q']"

    - name: Open terminal with <Super>+Return name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Open terminal'"
    - name: Open terminal with <Super>+Return binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Super>Return'"
    - name: Open terminal with <Super>+Return command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'gnome-terminal'"
    
    - name: Open browser shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'Open browser'"
    - name: Open browser binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Shift><Super>Return'"
    - name: Open browser binding command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'google-chrome-stable'"
    
    - name: Open nautilus shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name"
        value: "'Open nautilus'"
    - name: Open nautilus shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding"
        value: "'<Shift><Super>n'"
    - name: Open nautilus command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command"
        value: "'nautilus'"
    
    - name: Enable gnome-shell extensions (available after restarting)
      dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value:
          - appindicatorsupport@rgcjonas.gmail.com
          - just-perfection-desktop@just-perfection
          - screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
          - user-theme@gnome-shell-extensions.gcampax.github.com
          - workspace-indicator@gnome-shell-extensions.gcampax.github.com']
          - dash-to-dock@micxgx.gmail.com
          - ding@rastersoft.com

  become: true
  become_user: '{{ username }}'

