---
- name: Install cloud native packages
  tags: [dev, cloudnative, packages]
  block:
    - name: Install cloud native packages
      community.general.pacman:
        name:
          - aws-cli
          - kubectl
          - helm
    - name: Install cloud native packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - kind
          - kubectx
          - stern
          - google-cloud-sdk
      become: yes
      become_user: aur_builder
    - name: Install docker
      community.general.pacman:
        name:
          - docker
          - docker-compose
    - name: Add user paolo to docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
    - name: Enable docker service
      shell: systemctl enable docker

- name: Install base packages
  tags: [base, packages]
  block:
  - name: Install base packages
    community.general.pacman:
      name:
        - git
        - gparted
        - base-devel
        - dnsutils
        - dhcpcd
        - dmidecode
        - deja-dup
        - firefox
        - guvcview
        - htop
        - pacman-contrib
        - iproute2
        - neofetch
        - net-tools
        - dialog
        - wpa_supplicant        
        - tcpdump
        - thefuck
        - tmux
        - vim
        - telegram-desktop
        - zsh
  - name: Symlink vim to vi
    command: ln -sf /usr/bin/vim /usr/bin/vi
  - name: Install base packages from aur
    kewlfft.aur.aur:
      use: paru
      name:
        - google-chrome
        - slack-desktop
        - timeshift
        - timeshift-autosnap
        - visual-studio-code-bin
        - zoom
    become: yes
    become_user: aur_builder

- name: Install fonts
  tags: [system, fonts]
  community.general.pacman:
    name:
      - ttf-anonymous-pro
      - ttf-droid
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans
      - ttf-jetbrains-mono
      - ttf-lato
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-ubuntu-font-family
      - ttf-ibm-plex
