---
- name: Create an aur_builder user to install aur packages without password
  block:
  - name: Create the `aur_builder` user
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: Allow the `aur_builder` user to run `sudo makepkg` without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/makepkg'
      create: yes
      validate: 'visudo -cf %s'

- name: Install paru
  block:
    - name: Checkout paru
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/paru.git'
        dest: /tmp/paru
      become: yes
      become_user: aur_builder
    - name: Build and install paru
      shell: makepkg -si --noconfirm
      args:
        chdir: /tmp/paru
      become: yes
      become_user: aur_builder

- name: Install base packages
  community.general.pacman:
    name:
      - git
      - base-devel
      - dhcpcd
      - firefox
      - kubectl
      - iproute2 
      - net-tools 
      - dialog 
      - wpa_supplicant

- name: Install fonts
  community.general.pacman:
    name:
      - ttf-anonymous-pro
      - ttf-droid
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans 
      - ttf-jetbrains-mono
      - ttf-lato
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-ubuntu-font-family

- name: Install gnome 
  block:
    - name: Install packages
      community.general.pacman:
        name: 
          - gdm
          - xorg
          - gnome
          - gnome-extra
          - networkmanager
          - ntfs-3g
          - xorg-server
        state: present
        update_cache: yes
    - name: "Enable gdm"
      shell: systemctl enable gdm
    - name: "Enable NetworkManager"
      shell: systemctl enable NetworkManager

- name: Install nvidia drivers
  community.general.pacman:
    name: 
      - nvidia
      - nvidia-settings
      - nvidia-utils
    state: present
    update_cache: yes

- name: Install pipewire audio
  block:
    - name: Install pipewire packages
      shell: yes | pacman -Syu pipewire-pulse # there isn't a way to install conflicting packages.

- name: Install aur packages
  kewlfft.aur.aur:
    use: paru
    name:
      - zoom
      - slack-desktop
      - kind
      - kubectx
      - stern
      - google-chrome
  become: yes
  become_user: aur_builder

- name: Install docker
  block:
    - name: Install docker
      community.general.pacman:
        name:
          - docker
    - name: Add user paolo to docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
    - name: Enable docker service
      shell: systemctl enable docker

- name: Enable sshd.service
  shell: systemctl enable sshd