---
- name: Install multimedia packages
  tags: [packages, media]
  block:
    - name: Install media packages (aur)
      kewlfft.aur.aur:
        use: paru
        name:
          - kooha
          - mplayer
          - vlc
          - libmicrodns
          - protobuf
      become: yes
      become_user: aur_builder
