---
- name: Install logitech stuff
  tags: [system, grub]
  block:
  - name: Install logitech packages
    community.general.pacman:
      name:
        - solaar
  - name: Install logitech packages from aur
    kewlfft.aur.aur:
      use: paru
      name:
        - logiops
    become: yes
    become_user: aur_builder
  - name: Configure logiops (for MX Master 2S)
    ansible.builtin.copy:
      src: logitech/logid-mx-master2s.cfg
      dest: /etc/logid.cfg
