---
- name: Configure grub
  tags: [system, grub]
  block:
  - stat: path=/boot/grub
    register: grubcfg
  - name: "Configuring GRUB to print the OEM logo"
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=2 quiet splash"'
      mode: 0644
      backup: yes
  - name: Enable OS_PROBER
    lineinfile:
      dest: /etc/default/grub
      line: GRUB_DISABLE_OS_PROBER=false
      mode: 0644
      backup: yes
  - name: "Regenerate GRUB config"
    command: grub-mkconfig -o /boot/grub/grub.cfg
    when: grubcfg.stat.isdir is defined and grubcfg.stat.isdir

- name: Configure grub to print OEM logo
  tags: [system, grub]
  block:
  - name: "Configuring GRUB cmdline"
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=2 quiet splash"'
      mode: 0644
      backup: yes
  - stat: path=/boot/grub
    register: grubcfg
  - name: "Regenerate GRUB config"
    command: grub-mkconfig -o /boot/grub/grub.cfg
    when: grubcfg.stat.isdir is defined and grubcfg.stat.isdir
    