---
- name: Install Kernel
  tags: [system, kernel]
  block:
  - name: "Block linux upstream kernel"
    block:
    - stat: path=/boot/grub
      register: grubcfg

  - name: "Install linux-lts kernel"
    block:
    - name: Install lts kernel
      community.general.pacman:
        name:
          - linux-lts
          - linux-lts-headers
          - linux-firmware
        state: present
        update_cache: yes

    - name: Install linux kernel
      community.general.pacman:
        name:
          - linux
          - linux-headers
          - linux-firmware
        state: present
        update_cache: yes
    - name: Ensure other kernel are not installed
      community.general.pacman:
        name:
          - linux-zen
          - linux-zen-headers
        state: absent
        update_cache: yes
      ignore_errors: yes
    when: kernel == "standard"

  - name: "Linux zen kernel"
    block:
    - name: Install linux zen kernel
      community.general.pacman:
        name:
          - linux-zen
          - linux-zen-headers
          - linux-firmware
        state: present
        update_cache: yes
    - name: Ensure other kernel are not installed
      community.general.pacman:
        name:
          - linux
          - linux-headers
        state: absent
        update_cache: yes
      ignore_errors: yes
    when: kernel == "zen"

  - name: Copy provided mkinitcpio.conf
    ansible.builtin.copy:
      src: mkinitcpio.conf
      dest: /etc/mkinitcpio.conf

  - name: Regenerate mkinitcpio.conf
    shell: mkinitcpio -P

  - name: Regenerate grub config
    shell: grub-mkconfig -o /boot/grub/grub.cfg
    when: grubcfg.stat.isdir is defined and grubcfg.stat.isdir
